POST http://localhost:5400/books/new-book
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjlkNWM4NDhkLWM5Y2EtNDRhYi1hNGM4LTU5Nzg0NzBlYWNiOSIsImZpcnN0TmFtZSI6IkJpbGwiLCJsYXN0TmFtZSI6IkNsaW50b24iLCJwaG9uZU51bWJlciI6IjA3OTE3MzY1NzAiLCJlbWFpbCI6ImNsaW50b25hcmFuaUBnbWFpbC5jb20iLCJwcm9maWxlIjpudWxsLCJpc0NyZWF0ZWQiOnRydWUsInJvbGUiOiJvcmdhbml6ZXIiLCJpYXQiOjE3MjE4MzA5MDMsImV4cCI6MTcyMTgzODEwM30.QGsjlBsIPntxy2PkfXkg5S8qbZMA4JGZiXPdM-AeX90

{
  "UserId": "c85260a3-b04c-48dd-b6c4-9f364b4684fc",
  "EventId": "2402bb88-65c7-4da8-b2a0-9f10905639ad",
  "Type": "single",
  "NumberOfPeople": 1
}

# 
### Fetch All booked events
GET http://localhost:5400/books/all-bookings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjlkNWM4NDhkLWM5Y2EtNDRhYi1hNGM4LTU5Nzg0NzBlYWNiOSIsImZpcnN0TmFtZSI6IkJpbGwiLCJsYXN0TmFtZSI6IkNsaW50b24iLCJwaG9uZU51bWJlciI6IjA3OTE3MzY1NzAiLCJlbWFpbCI6ImNsaW50b25hcmFuaUBnbWFpbC5jb20iLCJwcm9maWxlIjpudWxsLCJpc0NyZWF0ZWQiOnRydWUsInJvbGUiOiJvcmdhbml6ZXIiLCJpYXQiOjE3MjE4MzA5MDMsImV4cCI6MTcyMTgzODEwM30.QGsjlBsIPntxy2PkfXkg5S8qbZMA4JGZiXPdM-AeX90

### Delete booked Event 
DELETE http://localhost:5400/books/delete-event/4ca776f0-4686-43b8-b8bd-0cff56303c21
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY0MjM3MWRjLWZjZDQtNDVmMi1iYTQyLTg4NTkzZDFjN2E4YiIsImZpcnN0TmFtZSI6IkFsbGFuIiwibGFzdE5hbWUiOiJPbWFyaSIsInBob25lTnVtYmVyIjoiMDc5MTczNjU3MiIsImVtYWlsIjoiYWxsYW5vbWFyaUBnbWFpbC5jb20iLCJwcm9maWxlIjpudWxsLCJpc0NyZWF0ZWQiOnRydWUsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzIxNTQ4OTU0LCJleHAiOjE3MjE1NTYxNTR9.Jvk0K2lw62AnqF0dDOYvhL1UGhJuaFaxkw7x0RMsHnc

### Get booked event by ID
GET http://localhost:5400/books/one-event/74266852-f6f7-4992-8def-fa002007e50e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY0MjM3MWRjLWZjZDQtNDVmMi1iYTQyLTg4NTkzZDFjN2E4YiIsImZpcnN0TmFtZSI6IkFsbGFuIiwibGFzdE5hbWUiOiJPbWFyaSIsInBob25lTnVtYmVyIjoiMDc5MTczNjU3MiIsImVtYWlsIjoiYWxsYW5vbWFyaUBnbWFpbC5jb20iLCJwcm9maWxlIjpudWxsLCJpc0NyZWF0ZWQiOnRydWUsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzIxNTQ4OTU0LCJleHAiOjE3MjE1NTYxNTR9.Jvk0K2lw62AnqF0dDOYvhL1UGhJuaFaxkw7x0RMsHnc
